pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            environment {
                XDG_CACHE_HOME = "${WORKSPACE}/.cache"
                GOCACHE        = "${WORKSPACE}/.cache/go-build"
            }
            steps {
                dir('bugtracker-backend') {
                    sh '''
                      mkdir -p "$XDG_CACHE_HOME" "$GOCACHE"
                      go version
                      go test -v ./...
                    '''
                }
            }
        }

        stage('Unit test -Frontend') {
            agent {
                docker {
                    image 'node:20-alpine'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-frontend') {
                    sh '''
                      npm ci
                      npm test
                    '''
                }
            }
            post {
                always {
                    junit 'bugtracker-frontend/test-results.xml'
                }
            }
        }
    }
}
